<?php 
/**
 * Copyright (c) 2014 Textmaster
*
* NOTICE OF LICENSE
*
* This source file is subject to the Open Software License (OSL 3.0)
* It is available through the world-wide-web at this URL:
* http://opensource.org/licenses/osl-3.0.php
*
* @category    Textmaster
* @package     Addonline_Textmaster
* @copyright   Copyright (c) 2014 Textmaster
* @author 	    Addonline (http://www.addonline.fr)
* @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/
?>
<script type="text/javascript">// <![CDATA[

function showAuthors(url) {
    winCompare = new Window({title:'<?php echo $_helper->__('Message to author for revision');  ?>',width:820,height:160,minimizable:false,maximizable:false,showEffectOptions:{duration:0.4},hideEffectOptions:{duration:0.4}});
    winCompare.setZIndex(100);
    //winCompare.getContent().update('<textarea class="textarea" id="messageRevision" style="width: 98%;height:100px;margin:10px 0px;" name="message"></textarea><button id="sendMessage" onclick="sendRevision();">Send</button>');
    winCompare.showCenter(true);
 
}
function sendRevision (){
	url = '<?php echo $this->getUrl('*/*/revision',array('id'=>$this->getDocument()->getId()));?>message/'+$('messageRevision').getValue();
	//console.log(url);
	window.location=url;
}
// ]]></script>