<?php
/**
 * Copyright (c) 2014 Textmaster
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    Textmaster
 * @package     Textmaster_Textmaster
 * @copyright   Copyright (c) 2014 Textmaster
 * @author 	    Addonline (http://www.addonline.fr)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$_support_messages = $this->getDocument()->getSupportMessages();

if(isset($_support_messages['support_messages']) && count($_support_messages['support_messages'])) : 
?>
<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-customer-view"><?php echo Mage::helper('textmaster')->__('Support messages'); ?></h4>
	</div>
	<br/>
	<?php foreach($_support_messages['support_messages'] as $message) : ?>
	<fieldset>
		<?php if($message['written_by_you']) : ?>
		<strong><?php echo Mage::helper('textmaster')->__('Written by %s ',Mage::helper('textmaster')->__('you'));?> <?php echo $this->formatTime($message['created_at']['full'], Mage_Core_Model_Locale::FORMAT_TYPE_SHORT,true);?></strong><br/>
		<?php else :?>
		<strong><?php echo Mage::helper('textmaster')->__('Written by %s ',$message['author_ref']);?> <?php echo $this->formatTime($message['created_at']['full'], Mage_Core_Model_Locale::FORMAT_TYPE_SHORT,true);?></strong><br/>
		<?php endif; ?>
		<?php echo $message['message']?>
	</fieldset>
	
	<?php endforeach; ?>
	
</div>
<?php endif; ?>