<?php 
/**
 * Copyright (c) 2014 Textmaster
*
* NOTICE OF LICENSE
*
* This source file is subject to the Open Software License (OSL 3.0)
* It is available through the world-wide-web at this URL:
* http://opensource.org/licenses/osl-3.0.php
*
* @category    Textmaster
* @package     Addonline_Textmaster
* @copyright   Copyright (c) 2014 Textmaster
* @author 	    Addonline (http://www.addonline.fr)
* @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/
?>
<div class="content-header">
    <h3 class="icon-head head-products"><?php echo Mage::helper('textmaster')->__('Translations');?></h3>
</div>
<?php
$user = Mage::helper('textmaster')->getApi()->getUserInfo();
if(!isset($user['email'])) { 
?>
<?php echo Mage::helper('textmaster')->__('Veuillez configurer le module Textmaster afin de traduire votre produit'); 
	return; ?>
<?php } ?>
<?php 
if (!$this->getRequest()->getParam('store')) {
	?>
    <ul class="messages" style="margin-bottom: 20px;"><li class="notice-msg"><?php echo $this->__('You are viewing default/website values. Please select a store view (from left) to see translation options.') ?></li></ul><?php
    return;
}
?>
<div style="margin-bottom: 30px;font-size:13px;"><a href="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/textmaster_project/createprojectfromproduct',array('id'=>Mage::app()->getRequest()->getParam('id'))); ?>"><?php echo Mage::helper('textmaster')->__('Translate product');?></a></div>