<?php
/**
 * Copyright (c) 2014 Textmaster
*
* NOTICE OF LICENSE
*
* This source file is subject to the Open Software License (OSL 3.0)
* It is available through the world-wide-web at this URL:
* http://opensource.org/licenses/osl-3.0.php
*
* @category    Textmaster
* @package     Addonline_Textmaster
* @copyright   Copyright (c) 2014 Textmaster
* @author 	    Addonline (http://www.addonline.fr)
* @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/
?>
<?php
/**
 * @see Mage_Adminhtml_Block_Widget_Form_Container
 */
 ?>
<?php echo $this->getFormInitScripts() ?>
<div class="content-header">
    <?php echo $this->getHeaderHtml() ?>
    <p class="form-buttons"><?php echo $this->getButtonsHtml('header') ?></p>
</div>
<div class="textmaster-introduction">
<?php echo $this->getIntroHtml() ?> 
Lorem ipsum dolor sit amet, labores alienum pri ex. 
No pri idque molestiae temporibus, eam quando detraxit at. 
Usu maiestatis sadipscing ad, sea te graece mnesarchum, nisl nemore denique ei his. 
Eu quo decore malorum omnesque, ne utroque lucilius vel. Mea solet pericula ut. Per ludus invenire te.
</div>
<?php echo $this->getFormHtml() ?>
<?php if ($this->hasFooterButtons()): ?>
    <div class="content-footer">
        <p class="form-buttons"><?php echo $this->getButtonsHtml('footer') ?></p>
    </div>
<?php endif; ?>
<script type="text/javascript">
    editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl() ?>');
</script>
<?php echo $this->getFormScripts() ?>
