<?php 
/**
 * Copyright (c) 2014 Textmaster
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
* @category    Textmaster
 * @package     Addonline_Textmaster
 * @copyright   Copyright (c) 2014 Textmaster
 * @author 	    Addonline (http://www.addonline.fr)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="textmaster-info">
	<span class="textmaster-email">
	<?php echo Mage::helper('textmaster')->__('Textmaster account'); ?> <?php echo $this->getEmail(); ?>
	</span>
	<span class="textmaster-credit">
	<?php echo Mage::helper('textmaster')->__('Credits:'); ?> <?php echo $this->getCredit(); ?>
	<a href="http://textmaster.com/clients/payment_requests/new" target="_blank" ><?php echo Mage::helper('textmaster')->__('Buy credits'); ?></a>
	</span>
	
</div>
