<?php 
/**
 * Copyright (c) 2014 Textmaster
*
* NOTICE OF LICENSE
*
* This source file is subject to the Open Software License (OSL 3.0)
* It is available through the world-wide-web at this URL:
* http://opensource.org/licenses/osl-3.0.php
*
* @category    Textmaster
* @package     Addonline_Textmaster
* @copyright   Copyright (c) 2014 Textmaster
* @author 	    Addonline (http://www.addonline.fr)
* @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/
?>
<p>
<?php
echo Mage::helper('textmaster')->__('You need to be logged in to use this plugin.');
?>
<br/>
<a href="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/system_config/edit/section/textmaster'); ?>">
<?php
echo Mage::helper('textmaster')->__('Click here to log in or to create a TextMaster account.');
?>
</a>
</p>
